baseURL = 'https://arunta.co.in'
languageCode = 'en-us'
title = 'Deep N Wide'
theme = "PaperMod"
googleAnalytics = 'G-E5SKNTC5DT' # <--- Replace with your ID once found

[outputs]
    home = ["HTML", "RSS", "JSON"]

[params]
    # 1. Custom Copyright & Footer Cleanup
    copyright = "© 2024 Arun T Anandhakrishnan"
    disableFinishedParsingByHugo = true # Hides "Powered by Hugo"

    # 2. Back to Top Button
    ShowScrollToTop = true 

    # 3. Favicon (Place favicon.png in static/ folder)
    [params.assets]
        favicon = "/favicon.png"

    # 4. Profile Label
    [params.label]
        text = "Deep N Wide"
        icon = "/images/arunta-profile.jpg"
        iconHeight = 35

    [params.profileMode]
        enabled = false

# 5. Top Navigation Menu (MUST be outside of [params])
[[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 5

[[menu.main]]
    identifier = "facebook"
    name = "Facebook"
    url = "https://www.facebook.com/arun.t.anandhakrishnan"
    weight = 10

[[menu.main]]
    identifier = "instagram"
    name = "Instagram"
    url = "https://www.instagram.com/arun.t.anandhakrishnan/"
    weight = 20
    
