baseURL = 'https://arunta.co.in'
languageCode = 'en-us'
title = 'Deep N Wide'
theme = "PaperMod"
googleAnalytics = 'G-E5SKNTC5DT' # <--- Replace with your ID once found

[outputs]
    home = ["HTML", "RSS", "JSON"]

[params]
    # This disables the "feature" styling for the first post
    mainSections = ["posts"]
    
    # Add this line to force all posts to look like regular entries
    displayFullContent = false 

    # Shows this image in link previews
    images = ["/images/arunta-profile.jpg"] 

    # Shows the tags at the bottom of each post
    ShowPostNavLinks = true

    # Allows users to click tags to see all related posts
    showFullTextContent = false 

    # Custom Copyright & Footer Cleanup
    copyright = "© 2024 Arun T Anandhakrishnan"

    disableFinishedParsingByHugo = true # Hides "Powered by Hugo"
    
    hideFooter = false

    # Back to Top Button
    ShowScrollToTop = true 

    # Favicon (Place favicon.png in static/ folder)
    [params.assets]
        favicon = "/favicon.png"
        favicon16x16 = "/favicon.png"
        favicon32x32 = "/favicon.png"
        apple_touch_icon = "/favicon.png"

    # Profile Label
    [params.label]
        text = "Deep N Wide"
        icon = "/images/arunta-profile.jpg"
        iconHeight = 35

    [params.profileMode]
        enabled = false

# Top Navigation Menu (MUST be outside of [params])
[[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
    weight = 5

[[menu.main]]
    identifier = "facebook"
    name = "Facebook"
    url = "https://www.facebook.com/arun.t.anandhakrishnan"
    weight = 10

[[menu.main]]
    identifier = "instagram"
    name = "Instagram"
    url = "https://www.instagram.com/arun.t.anandhakrishnan/"
    weight = 20
    
[[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 2  # Moves it to the left side of the menu

[[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 3

[[menu.main]]
    identifier = "archive"
    name = "Archive"
    url = "/archives/"
    weight = 1
